version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3003:3000"
    command: sh -c "npm install && npm run build && npm start"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
